#
# ==== General info ====
#
# * After editing of this file you need to check server logs to be
# sure that no errors was appeared.
#

#
# Show debug info. Possible values: true | false (default = false)
#
# This option can affect the performance.
#
debug: false

#
# Increase density according to distance from the map center.
#
# Use 0 to disable the feature.
#

distance-density-multiplier: 5_000

# Used for nether-specific generation
nether-name: world_nether

# Used for end-specific generation
end-name: world_the_end