name: SecretRooms
main: com.gmail.uprial.secretrooms.SecretRooms
version: 0.11.5
api-version: 1.21
commands:
  secretrooms:
    description: SecretRooms config help
    usage: /secretrooms help
    permission:
    permission-message:
permissions:
  secretrooms.repopulate-loaded:
    description: Gives access to SecretRooms 'repopulate-loaded' command
    default: op
  secretrooms.claim:
    description: Gives access to SecretRooms 'claim' command
    default: op
  secretrooms.break:
    description: Gives access to SecretRooms 'break' command
    default: op
  secretrooms.loaded-stats:
    description: Gives access to SecretRooms 'loaded-stats' command
    default: op
  secretrooms.loaded-locations:
    description: Gives access to SecretRooms 'loaded-locations' command
    default: op
