package com.gmail.uprial.railnet.populator.railway.schema;

import org.bukkit.block.Biome;

// Currently, this enum is needed for debugging and testing purposes only.
public enum BiomeEnum {
    OCEAN(Biome.OCEAN),
    PLAINS(Biome.PLAINS),
    DESERT(Biome.DESERT),
    WINDSWEPT_HILLS(Biome.WINDSWEPT_HILLS),
    FOREST(Biome.FOREST),
    TAIGA(Biome.TAIGA),
    SWAMP(Biome.SWAMP),
    MANGROVE_SWAMP(Biome.MANGROVE_SWAMP),
    RIVER(Biome.RIVER),
    NETHER_WASTES(Biome.NETHER_WASTES),
    THE_END(Biome.THE_END),
    FROZEN_OCEAN(Biome.FROZEN_OCEAN),
    FROZEN_RIVER(Biome.FROZEN_RIVER),
    SNOWY_PLAINS(Biome.SNOWY_PLAINS),
    MUSHROOM_FIELDS(Biome.MUSHROOM_FIELDS),
    BEACH(Biome.BEACH),
    JUNGLE(Biome.JUNGLE),
    SPARSE_JUNGLE(Biome.SPARSE_JUNGLE),
    DEEP_OCEAN(Biome.DEEP_OCEAN),
    STONY_SHORE(Biome.STONY_SHORE),
    SNOWY_BEACH(Biome.SNOWY_BEACH),
    BIRCH_FOREST(Biome.BIRCH_FOREST),
    DARK_FOREST(Biome.DARK_FOREST),
    SNOWY_TAIGA(Biome.SNOWY_TAIGA),
    OLD_GROWTH_PINE_TAIGA(Biome.OLD_GROWTH_PINE_TAIGA),
    WINDSWEPT_FOREST(Biome.WINDSWEPT_FOREST),
    SAVANNA(Biome.SAVANNA),
    SAVANNA_PLATEAU(Biome.SAVANNA_PLATEAU),
    BADLANDS(Biome.BADLANDS),
    WOODED_BADLANDS(Biome.WOODED_BADLANDS),
    SMALL_END_ISLANDS(Biome.SMALL_END_ISLANDS),
    END_MIDLANDS(Biome.END_MIDLANDS),
    END_HIGHLANDS(Biome.END_HIGHLANDS),
    END_BARRENS(Biome.END_BARRENS),
    WARM_OCEAN(Biome.WARM_OCEAN),
    LUKEWARM_OCEAN(Biome.LUKEWARM_OCEAN),
    COLD_OCEAN(Biome.COLD_OCEAN),
    DEEP_LUKEWARM_OCEAN(Biome.DEEP_LUKEWARM_OCEAN),
    DEEP_COLD_OCEAN(Biome.DEEP_COLD_OCEAN),
    DEEP_FROZEN_OCEAN(Biome.DEEP_FROZEN_OCEAN),
    THE_VOID(Biome.THE_VOID),
    SUNFLOWER_PLAINS(Biome.SUNFLOWER_PLAINS),
    WINDSWEPT_GRAVELLY_HILLS(Biome.WINDSWEPT_GRAVELLY_HILLS),
    FLOWER_FOREST(Biome.FLOWER_FOREST),
    ICE_SPIKES(Biome.ICE_SPIKES),
    OLD_GROWTH_BIRCH_FOREST(Biome.OLD_GROWTH_BIRCH_FOREST),
    OLD_GROWTH_SPRUCE_TAIGA(Biome.OLD_GROWTH_SPRUCE_TAIGA),
    WINDSWEPT_SAVANNA(Biome.WINDSWEPT_SAVANNA),
    ERODED_BADLANDS(Biome.ERODED_BADLANDS),
    BAMBOO_JUNGLE(Biome.BAMBOO_JUNGLE),
    SOUL_SAND_VALLEY(Biome.SOUL_SAND_VALLEY),
    CRIMSON_FOREST(Biome.CRIMSON_FOREST),
    WARPED_FOREST(Biome.WARPED_FOREST),
    BASALT_DELTAS(Biome.BASALT_DELTAS),
    DRIPSTONE_CAVES(Biome.DRIPSTONE_CAVES),
    LUSH_CAVES(Biome.LUSH_CAVES),
    DEEP_DARK(Biome.DEEP_DARK),
    MEADOW(Biome.MEADOW),
    GROVE(Biome.GROVE),
    SNOWY_SLOPES(Biome.SNOWY_SLOPES),
    FROZEN_PEAKS(Biome.FROZEN_PEAKS),
    JAGGED_PEAKS(Biome.JAGGED_PEAKS),
    STONY_PEAKS(Biome.STONY_PEAKS),
    CHERRY_GROVE(Biome.CHERRY_GROVE);

    private final Biome biome;

    BiomeEnum(final Biome biome) {
        this.biome = biome;
    }

    public Biome getBiome() {
        return biome;
    }
}
